import type { Metadata } from "next";
import { Cormorant_Garamond, Merriweather_Sans } from "next/font/google";
import "./globals.css";

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
  weight: "300",
});

const merriweatherSans = Merriweather_Sans({
  variable: "--font-merriweather-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cormorantGaramond.variable} ${merriweatherSans.variable} antialiased`}
        style={{ fontFamily: "var(--font-merriweather-sans), sans-serif" }}
      >
        <style>
          {`
            h1, h2, h3, h4, h5, h6 {
              font-family: var(--font-cormorant-garamond), sans-serif;
            }
          `}
        </style>
        {children}
      </body>
    </html>
  );
}
